url: "https://landingpageku.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Landing Page ku" # the name of your site, e.g. ACME Corp.

sass:
 style: compressed

plugins:
 - jekyll-sitemap